[package]
authors = ["Maximilian Goisser <goisser94@gmail.com>"]
name = "rsdocs-dashing"
version = "0.1.0"

[dependencies]
copy_dir = "0.1.2"
docopt = "0.8.1"
glob = "0.2.11"
serde = "1.0.11"
serde_derive = "1.0.11"
serde_json = "1.0.2"
